version: 0.2

phases:

  install:
    commands:
      - npm install
  pre_build:
    commands:
  build:
    commands:
      - echo we be buildn
      - npm run build
  post_build:
    commands:
      

      - bash -c 'if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then curl -X GET "https://10zbellahd.execute-api.eu-west-2.amazonaws.com/default/discordGitInfo?msg=Build%20Failed%20Sucessfully" exit; fi'

      - aws s3 sync ./dist $S3_BUCKET
      - echo CODEBUILD_BUILD_SUCCEEDING
      - curl -X GET "https://10zbellahd.execute-api.eu-west-2.amazonaws.com/default/discordGitInfo?msg=Build%20Success"
artifacts:
  files:
    - '**/*'
  base-directory: dist
