version: 0.2

phases:

  variables: 
    buildSucc: "Build Failed Succesfully"

  install:
    commands:
      - npm install
  pre_build:
    commands:
  build:
    commands:
      - echo we be buildn
      - npm run build
  post_build:
    commands:
      
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"1/" ]; then buildSucc = "Build Succesfull"; fi"
      - aws s3 sync ./dist $S3_BUCKET
      - echo CODEBUILD_BUILD_SUCCEEDING
      - echo $buildSucc
      - curl https://10zbellahd.execute-api.eu-west-2.amazonaws.com/default/discordGitInfo?msg=$buildSucc
artifacts:
  files:
    - '**/*'
  base-directory: dist